version: '3'
services:
    client:
        build: ./client
        command: npm start
        volumes:
            - ./client:/usr/src/app
        ports:
            - "3000:3000"
        depends_on:
            - server
            
    db:
        image: postgres:latest
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: buildings
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - "5432:5432"
        volumes:
          - ./server/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        
    server:
        build: ./server
        volumes:
            - ./server:/usr/local/go/src/app
        command: sh -c "go build -gcflags='all=-N -l' -o main ./cmd/api && /go/bin/dlv exec ./main --continue --accept-multiclient --api-version=2 --headless --listen=:40000"
        # command: go run ./cmd/api
        ports:
            - "8080:8080"
            - "40000:40000"
        
        