version: '3'
services:
    client:
        build: ./client
        # command: npm start
        # volumes:
        #     - ./client:/usr/src/app
        # command: npm run build
        environment:
            - NODE_ENV=production
        ports:
            # - "3000:3000"
            - "80:80"
        depends_on:
            - server
            
    db:
        image: postgres:latest
        restart: always
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: movies
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - "5432:5432"
        volumes:
          # - ./postgres-data:/var/lib/postgresql/data
          - ./server/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        
    server:
        build: ./server
        volumes:
            - ./server:/usr/local/go/src/app
        command: go run ./cmd/api
        ports:
            - "8080:8080"
        
