FROM golang:1.19-alpine

WORKDIR /usr/local/go/src/server

COPY go.mod go.sum ./

RUN go get -u github.com/jackc/pgx/v4 && \
    go get -u github.com/jackc/pgconn && \
    go get -u golang.org/x/crypto/bcrypt && \
    go get github.com/gin-gonic/gin && \
    apk update && apk add --no-cache gcc libc-dev

COPY . .

RUN go build -o ./cmd/api/main ./cmd/api/

EXPOSE 8080

CMD ["./cmd/api/main"]
