name: Continuous Deployment

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  # merge:
  #   needs: [wait_for_frontend_test, wait_for_backend_test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Merge to main
  #       run: git merge --ff-only ${{ github.ref }}
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    # needs: merge
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: 580481854598.dkr.ecr.us-west-2.amazonaws.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::580481854598:role/my-github-actions-role
          aws-region: us-west-2
          role-duration-seconds: 3600

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
        # with:
        #   registries: ${{ env.ECR_REGISTRY }}

      - name: Print name of ECR
        run : echo "env ecr - ${{ env.ECR_REGISTRY }}"

      # - name: Build and push Go Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./server/Dockerfile.prod
      #     push: true
      #     tags: ${{ env.ECR_REGISTRY }}/go:${{ github.sha }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Go Docker image
        working-directory: ./server
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: go
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f ./Dockerfile.prod -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Build and push Nginx-React Docker image
        working-directory: ./client
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: nginx-react
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f ./Dockerfile.prod -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Apply Terraform configuration
        working-directory: ./terraform
        run: >
          terraform apply -auto-approve
          -var="go_image=${{ env.ECR_REGISTRY }}/go:${{ github.sha }}"
          -var="nginx_image=${{ env.ECR_REGISTRY }}/nginx-react:${{ github.sha }}"
          .

