name: Merge Code

on:
  push:
    branches: [main]

  workflow_run:
    workflows: [ Frontend Test ]
    types:
      - completed

jobs:
  merge:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge to main
        run: git merge --ff-only ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}